// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("md5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha1"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * ScanResult represents a single scan result
 */
export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("engine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engine"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

/**
 * StatsInfo 统计信息
 */
export class StatsInfo {
    /**
     * Creates a new StatsInfo instance.
     * @param {Partial<StatsInfo>} [$$source = {}] - The source object to create the StatsInfo.
     */
    constructor($$source = {}) {
        if (!("malicious" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["malicious"] = 0;
        }
        if (!("suspicious" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["suspicious"] = 0;
        }
        if (!("harmless" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["harmless"] = 0;
        }
        if (!("undetected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["undetected"] = 0;
        }
        if (!("typeUnsupported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["typeUnsupported"] = 0;
        }
        if (!("confirmedTimeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confirmedTimeout"] = 0;
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("failure" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failure"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsInfo(/** @type {Partial<StatsInfo>} */($$parsedSource));
    }
}

/**
 * Task represents a scan task
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analysisId"] = "";
        }
        if (!("md5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha1"] = "";
        }
        if (!("scanTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scanTime"] = "";
        }
        if (!("detectionRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detectionRate"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {ScanResult[]}
             */
            this["results"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {StatsInfo}
             */
            this["stats"] = (new StatsInfo());
        }
        if (!("fileInfo" in $$source)) {
            /**
             * @member
             * @type {FileInfo}
             */
            this["fileInfo"] = (new FileInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField11_0($$parsedSource["results"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField12_0($$parsedSource["stats"]);
        }
        if ("fileInfo" in $$parsedSource) {
            $$parsedSource["fileInfo"] = $$createField13_0($$parsedSource["fileInfo"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * VTTask VirusTotal 任务（用于前端展示）
 */
export class VTTask {
    /**
     * Creates a new VTTask instance.
     * @param {Partial<VTTask>} [$$source = {}] - The source object to create the VTTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("taskType" in $$source)) {
            /**
             * 任务类型: single/directory
             * @member
             * @type {string}
             */
            this["taskType"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analysisId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["completedAt"] = null;
        }
        if (!("md5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha1"] = "";
        }
        if (!("detectionRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detectionRate"] = 0;
        }
        if (!("totalEngines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalEngines"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {ScanResult[]}
             */
            this["results"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {StatsInfo}
             */
            this["stats"] = (new StatsInfo());
        }
        if (!("fileInfo" in $$source)) {
            /**
             * @member
             * @type {FileInfo}
             */
            this["fileInfo"] = (new FileInfo());
        }
        if (!("scanTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scanTime"] = "";
        }
        if (!("totalFiles" in $$source)) {
            /**
             * 目录扫描专用字段
             * 目录下文件总数
             * @member
             * @type {number}
             */
            this["totalFiles"] = 0;
        }
        if (!("maliciousFiles" in $$source)) {
            /**
             * 带毒文件数
             * @member
             * @type {number}
             */
            this["maliciousFiles"] = 0;
        }
        if (!("suspiciousFiles" in $$source)) {
            /**
             * 可疑文件数
             * @member
             * @type {number}
             */
            this["suspiciousFiles"] = 0;
        }
        if (!("completedFiles" in $$source)) {
            /**
             * 已完成扫描文件数
             * @member
             * @type {number}
             */
            this["completedFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VTTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VTTask}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField14_0($$parsedSource["results"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField15_0($$parsedSource["stats"]);
        }
        if ("fileInfo" in $$parsedSource) {
            $$parsedSource["fileInfo"] = $$createField16_0($$parsedSource["fileInfo"]);
        }
        return new VTTask(/** @type {Partial<VTTask>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ScanResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = StatsInfo.createFrom;
const $$createType3 = FileInfo.createFrom;
