// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    "md5": string;
    "sha256": string;
    "sha1": string;
    "size": number;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            this["sha1"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * ScanResult represents a single scan result
 */
export class ScanResult {
    "engine": string;
    "category": string;
    "result": string;
    "method": string;
    "detected": boolean;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("detected" in $$source)) {
            this["detected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

/**
 * StatsInfo 统计信息
 */
export class StatsInfo {
    "malicious": number;
    "suspicious": number;
    "harmless": number;
    "undetected": number;
    "typeUnsupported": number;
    "confirmedTimeout": number;
    "timeout": number;
    "failure": number;

    /** Creates a new StatsInfo instance. */
    constructor($$source: Partial<StatsInfo> = {}) {
        if (!("malicious" in $$source)) {
            this["malicious"] = 0;
        }
        if (!("suspicious" in $$source)) {
            this["suspicious"] = 0;
        }
        if (!("harmless" in $$source)) {
            this["harmless"] = 0;
        }
        if (!("undetected" in $$source)) {
            this["undetected"] = 0;
        }
        if (!("typeUnsupported" in $$source)) {
            this["typeUnsupported"] = 0;
        }
        if (!("confirmedTimeout" in $$source)) {
            this["confirmedTimeout"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("failure" in $$source)) {
            this["failure"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsInfo($$parsedSource as Partial<StatsInfo>);
    }
}

/**
 * Task represents a scan task
 */
export class Task {
    "id": string;
    "fileName": string;
    "filePath": string;
    "fileSize": number;
    "status": string;
    "analysisId": string;
    "md5": string;
    "sha256": string;
    "sha1": string;
    "scanTime": string;
    "detectionRate": number;
    "results": ScanResult[];
    "stats": StatsInfo;
    "fileInfo": FileInfo;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            this["analysisId"] = "";
        }
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            this["sha1"] = "";
        }
        if (!("scanTime" in $$source)) {
            this["scanTime"] = "";
        }
        if (!("detectionRate" in $$source)) {
            this["detectionRate"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new StatsInfo());
        }
        if (!("fileInfo" in $$source)) {
            this["fileInfo"] = (new FileInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField11_0($$parsedSource["results"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField12_0($$parsedSource["stats"]);
        }
        if ("fileInfo" in $$parsedSource) {
            $$parsedSource["fileInfo"] = $$createField13_0($$parsedSource["fileInfo"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

/**
 * VTTask VirusTotal 任务（用于前端展示）
 */
export class VTTask {
    "id": string;

    /**
     * 任务类型: single/directory
     */
    "taskType": string;
    "fileName": string;
    "filePath": string;
    "fileSize": number;
    "status": string;
    "analysisId": string;
    "createdAt": time$0.Time;
    "completedAt": time$0.Time;
    "md5": string;
    "sha256": string;
    "sha1": string;
    "detectionRate": number;
    "totalEngines": number;
    "results": ScanResult[];
    "stats": StatsInfo;
    "fileInfo": FileInfo;
    "scanTime": string;

    /**
     * 目录扫描专用字段
     * 目录下文件总数
     */
    "totalFiles": number;

    /**
     * 带毒文件数
     */
    "maliciousFiles": number;

    /**
     * 可疑文件数
     */
    "suspiciousFiles": number;

    /**
     * 已完成扫描文件数
     */
    "completedFiles": number;

    /** Creates a new VTTask instance. */
    constructor($$source: Partial<VTTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskType" in $$source)) {
            this["taskType"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            this["analysisId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = null;
        }
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            this["sha1"] = "";
        }
        if (!("detectionRate" in $$source)) {
            this["detectionRate"] = 0;
        }
        if (!("totalEngines" in $$source)) {
            this["totalEngines"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new StatsInfo());
        }
        if (!("fileInfo" in $$source)) {
            this["fileInfo"] = (new FileInfo());
        }
        if (!("scanTime" in $$source)) {
            this["scanTime"] = "";
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("maliciousFiles" in $$source)) {
            this["maliciousFiles"] = 0;
        }
        if (!("suspiciousFiles" in $$source)) {
            this["suspiciousFiles"] = 0;
        }
        if (!("completedFiles" in $$source)) {
            this["completedFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VTTask instance from a string or object.
     */
    static createFrom($$source: any = {}): VTTask {
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField14_0($$parsedSource["results"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField15_0($$parsedSource["stats"]);
        }
        if ("fileInfo" in $$parsedSource) {
            $$parsedSource["fileInfo"] = $$createField16_0($$parsedSource["fileInfo"]);
        }
        return new VTTask($$parsedSource as Partial<VTTask>);
    }
}

// Private type creation functions
const $$createType0 = ScanResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = StatsInfo.createFrom;
const $$createType3 = FileInfo.createFrom;
