// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VTService provides file-related operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * OpenFileDialog opens a file dialog and returns the selected file path.
 */
export function OpenFileDialog(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(740829225) as any;
    return $resultPromise;
}

/**
 * OpenFileDialogs opens a file dialog and returns the selected file paths.
 */
export function OpenFileDialogs(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3711403438) as any;
    return $resultPromise;
}
