// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VTService provides file-related operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckAnalysisStatus 检查分析状态
 * @param {string} taskID
 * @returns {Promise<$models.VTTask | null> & { cancel(): void }}
 */
export function CheckAnalysisStatus(taskID) {
    let $resultPromise = /** @type {any} */($Call.ByID(598662897, taskID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * CreateDirectoryScanTask 创建目录批量扫描任务
 * @param {string} directoryPath
 * @returns {Promise<$models.VTTask | null> & { cancel(): void }}
 */
export function CreateDirectoryScanTask(directoryPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1925676754, directoryPath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * CreateScanTask 创建扫描任务并上传文件
 * @param {string} filePath
 * @returns {Promise<$models.VTTask | null> & { cancel(): void }}
 */
export function CreateScanTask(filePath) {
    let $resultPromise = /** @type {any} */($Call.ByID(360281883, filePath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteTask 删除任务
 * @param {string} taskID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteTask(taskID) {
    let $resultPromise = /** @type {any} */($Call.ByID(4162849889, taskID));
    return $resultPromise;
}

/**
 * GetAPIKey 获取当前 API Key
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetAPIKey() {
    let $resultPromise = /** @type {any} */($Call.ByID(325723842));
    return $resultPromise;
}

/**
 * GetAllTasks 获取所有任务
 * @returns {Promise<($models.VTTask | null)[]> & { cancel(): void }}
 */
export function GetAllTasks() {
    let $resultPromise = /** @type {any} */($Call.ByID(3330197066));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAnalysis gets the analysis result from VirusTotal
 * @param {string} analysisID
 * @returns {Promise<$models.Task | null> & { cancel(): void }}
 */
export function GetAnalysis(analysisID) {
    let $resultPromise = /** @type {any} */($Call.ByID(1267140751, analysisID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetConcurrency 获取并发扫描数
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetConcurrency() {
    let $resultPromise = /** @type {any} */($Call.ByID(1323754804));
    return $resultPromise;
}

/**
 * GetFileDetail 获取文件详情
 * @param {string} fileID
 * @returns {Promise<store$0.VTFile | null> & { cancel(): void }}
 */
export function GetFileDetail(fileID) {
    let $resultPromise = /** @type {any} */($Call.ByID(1340957254, fileID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType6($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetFileInfo 获取文件信息
 * @param {string} filePath
 * @returns {Promise<[string, number]> & { cancel(): void }}
 */
export function GetFileInfo(filePath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1756313475, filePath));
    return $resultPromise;
}

/**
 * GetTask 获取单个任务
 * @param {string} taskID
 * @returns {Promise<$models.VTTask | null> & { cancel(): void }}
 */
export function GetTask(taskID) {
    let $resultPromise = /** @type {any} */($Call.ByID(745305392, taskID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetTaskFiles 获取任务下所有文件
 * @param {string} taskID
 * @returns {Promise<(store$0.VTFile | null)[]> & { cancel(): void }}
 */
export function GetTaskFiles(taskID) {
    let $resultPromise = /** @type {any} */($Call.ByID(2598262735, taskID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType7($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenFileDialog opens a file dialog and returns the selected file path.
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenFileDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(740829225));
    return $resultPromise;
}

/**
 * OpenFileDialogs opens a directory dialog and returns the selected directory path.
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenFileDialogs() {
    let $resultPromise = /** @type {any} */($Call.ByID(3711403438));
    return $resultPromise;
}

/**
 * RefreshFileStatus 刷新文件扫描状态
 * @param {string} fileID
 * @returns {Promise<store$0.VTFile | null> & { cancel(): void }}
 */
export function RefreshFileStatus(fileID) {
    let $resultPromise = /** @type {any} */($Call.ByID(296354214, fileID));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType6($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SetAPIKey sets the API key for VirusTotal
 * @param {string} apiKey
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetAPIKey(apiKey) {
    let $resultPromise = /** @type {any} */($Call.ByID(2464338774, apiKey));
    return $resultPromise;
}

/**
 * SetConcurrency 设置并发扫描数
 * @param {number} concurrency
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetConcurrency(concurrency) {
    let $resultPromise = /** @type {any} */($Call.ByID(1756967824, concurrency));
    return $resultPromise;
}

/**
 * UploadFile uploads a file to VirusTotal for scanning
 * @param {string} filePath
 * @returns {Promise<$models.Task | null> & { cancel(): void }}
 */
export function UploadFile(filePath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1508833308, filePath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.VTTask.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Task.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = store$0.VTFile.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
