// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add 添加分类
 */
export function Add(name: string, color: string): Promise<$models.Category | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1463987814, name, color) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Delete 删除分类
 */
export function Delete(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(305418816, id) as any;
    return $resultPromise;
}

/**
 * GetAll 获取所有分类
 */
export function GetAll(): Promise<$models.Category[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3116086716) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Update 更新分类
 */
export function Update(id: number, name: string, color: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(175497538, id, name, color) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
