// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add 添加分类
 * @param {string} name
 * @param {string} color
 * @returns {Promise<$models.Category | null> & { cancel(): void }}
 */
export function Add(name, color) {
    let $resultPromise = /** @type {any} */($Call.ByID(1463987814, name, color));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Delete 删除分类
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Delete(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(305418816, id));
    return $resultPromise;
}

/**
 * GetAll 获取所有分类
 * @returns {Promise<$models.Category[]> & { cancel(): void }}
 */
export function GetAll() {
    let $resultPromise = /** @type {any} */($Call.ByID(3116086716));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Update 更新分类
 * @param {number} id
 * @param {string} name
 * @param {string} color
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Update(id, name, color) {
    let $resultPromise = /** @type {any} */($Call.ByID(175497538, id, name, color));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Category.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
