// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Category {
    "id": number;
    "name": string;
    "color": string;
    "sort_order": number;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category($$parsedSource as Partial<Category>);
    }
}
