// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class InfoStat {
    "cpu": number;
    "vendorId": string;
    "family": string;
    "model": string;
    "stepping": number;
    "physicalId": string;
    "coreId": string;
    "cores": number;
    "modelName": string;
    "mhz": number;
    "cacheSize": number;
    "flags": string[];
    "microcode": string;

    /** Creates a new InfoStat instance. */
    constructor($$source: Partial<InfoStat> = {}) {
        if (!("cpu" in $$source)) {
            this["cpu"] = 0;
        }
        if (!("vendorId" in $$source)) {
            this["vendorId"] = "";
        }
        if (!("family" in $$source)) {
            this["family"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("stepping" in $$source)) {
            this["stepping"] = 0;
        }
        if (!("physicalId" in $$source)) {
            this["physicalId"] = "";
        }
        if (!("coreId" in $$source)) {
            this["coreId"] = "";
        }
        if (!("cores" in $$source)) {
            this["cores"] = 0;
        }
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("mhz" in $$source)) {
            this["mhz"] = 0;
        }
        if (!("cacheSize" in $$source)) {
            this["cacheSize"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = [];
        }
        if (!("microcode" in $$source)) {
            this["microcode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoStat instance from a string or object.
     */
    static createFrom($$source: any = {}): InfoStat {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField11_0($$parsedSource["flags"]);
        }
        return new InfoStat($$parsedSource as Partial<InfoStat>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
