// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class InfoStat {
    /**
     * Creates a new InfoStat instance.
     * @param {Partial<InfoStat>} [$$source = {}] - The source object to create the InfoStat.
     */
    constructor($$source = {}) {
        if (!("cpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpu"] = 0;
        }
        if (!("vendorId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vendorId"] = "";
        }
        if (!("family" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["family"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("stepping" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stepping"] = 0;
        }
        if (!("physicalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["physicalId"] = "";
        }
        if (!("coreId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["coreId"] = "";
        }
        if (!("cores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cores"] = 0;
        }
        if (!("modelName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelName"] = "";
        }
        if (!("mhz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mhz"] = 0;
        }
        if (!("cacheSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cacheSize"] = 0;
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["flags"] = [];
        }
        if (!("microcode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["microcode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InfoStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InfoStat}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField11_0($$parsedSource["flags"]);
        }
        return new InfoStat(/** @type {Partial<InfoStat>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
