// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cpu$0 from "../../../../../shirou/gopsutil/v3/cpu/models.js";

/**
 * CPUInfo CPU 使用率信息
 */
export class CPUInfo {
    /**
     * Creates a new CPUInfo instance.
     * @param {Partial<CPUInfo>} [$$source = {}] - The source object to create the CPUInfo.
     */
    constructor($$source = {}) {
        if (!("core_usages" in $$source)) {
            /**
             * 每核使用率（单位：百分比）
             * @member
             * @type {number[]}
             */
            this["core_usages"] = [];
        }
        if (!("core_info" in $$source)) {
            /**
             * CPU 信息
             * @member
             * @type {cpu$0.InfoStat}
             */
            this["core_info"] = (new cpu$0.InfoStat());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CPUInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("core_usages" in $$parsedSource) {
            $$parsedSource["core_usages"] = $$createField0_0($$parsedSource["core_usages"]);
        }
        if ("core_info" in $$parsedSource) {
            $$parsedSource["core_info"] = $$createField1_0($$parsedSource["core_info"]);
        }
        return new CPUInfo(/** @type {Partial<CPUInfo>} */($$parsedSource));
    }
}

/**
 * DiskInfo 磁盘使用信息
 */
export class DiskInfo {
    /**
     * Creates a new DiskInfo instance.
     * @param {Partial<DiskInfo>} [$$source = {}] - The source object to create the DiskInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * 挂载路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * 总容量（字节）
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * 已使用（字节）
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("used_percent" in $$source)) {
            /**
             * 使用率（百分比）
             * @member
             * @type {number}
             */
            this["used_percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskInfo(/** @type {Partial<DiskInfo>} */($$parsedSource));
    }
}

/**
 * HostInfo 主机信息
 */
export class HostInfo {
    /**
     * Creates a new HostInfo instance.
     * @param {Partial<HostInfo>} [$$source = {}] - The source object to create the HostInfo.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * 主机名
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * 操作系统
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * 平台
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("kernel_version" in $$source)) {
            /**
             * 内核版本
             * @member
             * @type {string}
             */
            this["kernel_version"] = "";
        }
        if (!("architecture" in $$source)) {
            /**
             * 架构
             * @member
             * @type {string}
             */
            this["architecture"] = "";
        }
        if (!("uptime_seconds" in $$source)) {
            /**
             * 运行时间（秒）
             * @member
             * @type {number}
             */
            this["uptime_seconds"] = 0;
        }
        if (!("uptime_readable" in $$source)) {
            /**
             * 运行时间（可读）
             * @member
             * @type {string}
             */
            this["uptime_readable"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostInfo(/** @type {Partial<HostInfo>} */($$parsedSource));
    }
}

/**
 * MemoryInfo 内存使用信息
 */
export class MemoryInfo {
    /**
     * Creates a new MemoryInfo instance.
     * @param {Partial<MemoryInfo>} [$$source = {}] - The source object to create the MemoryInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * 总内存（字节）
             * @member
             * @type {string}
             */
            this["total"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * 已使用（字节）
             * @member
             * @type {string}
             */
            this["used"] = "";
        }
        if (!("used_percent" in $$source)) {
            /**
             * 使用率（百分比）
             * @member
             * @type {number}
             */
            this["used_percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryInfo(/** @type {Partial<MemoryInfo>} */($$parsedSource));
    }
}

/**
 * NetworkInterface 网络接口信息
 */
export class NetworkInterface {
    /**
     * Creates a new NetworkInterface instance.
     * @param {Partial<NetworkInterface>} [$$source = {}] - The source object to create the NetworkInterface.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 接口名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mac" in $$source)) {
            /**
             * MAC 地址
             * @member
             * @type {string}
             */
            this["mac"] = "";
        }
        if (!("mtu" in $$source)) {
            /**
             * 最大传输单元
             * @member
             * @type {number}
             */
            this["mtu"] = 0;
        }
        if (!("isUp" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["isUp"] = false;
        }
        if (!("ipv4" in $$source)) {
            /**
             * IPv4 地址
             * @member
             * @type {string}
             */
            this["ipv4"] = "";
        }
        if (!("ipv6" in $$source)) {
            /**
             * IPv6 地址
             * @member
             * @type {string}
             */
            this["ipv6"] = "";
        }
        if (!("bytesSent" in $$source)) {
            /**
             * 发送字节数
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesRecv" in $$source)) {
            /**
             * 接收字节数
             * @member
             * @type {number}
             */
            this["bytesRecv"] = 0;
        }
        if (!("packetsSent" in $$source)) {
            /**
             * 发送包数
             * @member
             * @type {number}
             */
            this["packetsSent"] = 0;
        }
        if (!("packetsRecv" in $$source)) {
            /**
             * 接收包数
             * @member
             * @type {number}
             */
            this["packetsRecv"] = 0;
        }
        if (!("bytesSentRate" in $$source)) {
            /**
             * 每秒发送字节数
             * @member
             * @type {number}
             */
            this["bytesSentRate"] = 0;
        }
        if (!("bytesRecvRate" in $$source)) {
            /**
             * 每秒接收字节数
             * @member
             * @type {number}
             */
            this["bytesRecvRate"] = 0;
        }
        if (!("packetsSentRate" in $$source)) {
            /**
             * 每秒发送包数
             * @member
             * @type {number}
             */
            this["packetsSentRate"] = 0;
        }
        if (!("packetsRecvRate" in $$source)) {
            /**
             * 每秒接收包数
             * @member
             * @type {number}
             */
            this["packetsRecvRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkInterface}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInterface(/** @type {Partial<NetworkInterface>} */($$parsedSource));
    }
}

export class SysInfo {
    /**
     * Creates a new SysInfo instance.
     * @param {Partial<SysInfo>} [$$source = {}] - The source object to create the SysInfo.
     */
    constructor($$source = {}) {
        if (!("host_info" in $$source)) {
            /**
             * 主机信息
             * @member
             * @type {HostInfo | null}
             */
            this["host_info"] = null;
        }
        if (!("cpu_info" in $$source)) {
            /**
             * CPU 使用率信息
             * @member
             * @type {CPUInfo | null}
             */
            this["cpu_info"] = null;
        }
        if (!("memory_info" in $$source)) {
            /**
             * 内存使用信息
             * @member
             * @type {MemoryInfo | null}
             */
            this["memory_info"] = null;
        }
        if (!("disk_info" in $$source)) {
            /**
             * 磁盘使用信息
             * @member
             * @type {DiskInfo | null}
             */
            this["disk_info"] = null;
        }
        if (!("network_interfaces" in $$source)) {
            /**
             * 网络接口信息
             * @member
             * @type {NetworkInterface[]}
             */
            this["network_interfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SysInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SysInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("host_info" in $$parsedSource) {
            $$parsedSource["host_info"] = $$createField0_0($$parsedSource["host_info"]);
        }
        if ("cpu_info" in $$parsedSource) {
            $$parsedSource["cpu_info"] = $$createField1_0($$parsedSource["cpu_info"]);
        }
        if ("memory_info" in $$parsedSource) {
            $$parsedSource["memory_info"] = $$createField2_0($$parsedSource["memory_info"]);
        }
        if ("disk_info" in $$parsedSource) {
            $$parsedSource["disk_info"] = $$createField3_0($$parsedSource["disk_info"]);
        }
        if ("network_interfaces" in $$parsedSource) {
            $$parsedSource["network_interfaces"] = $$createField4_0($$parsedSource["network_interfaces"]);
        }
        return new SysInfo(/** @type {Partial<SysInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = cpu$0.InfoStat.createFrom;
const $$createType2 = HostInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = CPUInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = MemoryInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = DiskInfo.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = NetworkInterface.createFrom;
const $$createType11 = $Create.Array($$createType10);
