// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cpu$0 from "../../../../../shirou/gopsutil/v3/cpu/models.js";

/**
 * CPUInfo CPU 使用率信息
 */
export class CPUInfo {
    /**
     * 每核使用率（单位：百分比）
     */
    "core_usages": number[];

    /**
     * CPU 信息
     */
    "core_info": cpu$0.InfoStat;

    /** Creates a new CPUInfo instance. */
    constructor($$source: Partial<CPUInfo> = {}) {
        if (!("core_usages" in $$source)) {
            this["core_usages"] = [];
        }
        if (!("core_info" in $$source)) {
            this["core_info"] = (new cpu$0.InfoStat());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CPUInfo {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("core_usages" in $$parsedSource) {
            $$parsedSource["core_usages"] = $$createField0_0($$parsedSource["core_usages"]);
        }
        if ("core_info" in $$parsedSource) {
            $$parsedSource["core_info"] = $$createField1_0($$parsedSource["core_info"]);
        }
        return new CPUInfo($$parsedSource as Partial<CPUInfo>);
    }
}

/**
 * DiskInfo 磁盘使用信息
 */
export class DiskInfo {
    /**
     * 挂载路径
     */
    "path": string;

    /**
     * 总容量（字节）
     */
    "total": number;

    /**
     * 已使用（字节）
     */
    "used": number;

    /**
     * 使用率（百分比）
     */
    "used_percent": number;

    /** Creates a new DiskInfo instance. */
    constructor($$source: Partial<DiskInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            this["used"] = 0;
        }
        if (!("used_percent" in $$source)) {
            this["used_percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DiskInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskInfo($$parsedSource as Partial<DiskInfo>);
    }
}

/**
 * HostInfo 主机信息
 */
export class HostInfo {
    /**
     * 主机名
     */
    "hostname": string;

    /**
     * 操作系统
     */
    "os": string;

    /**
     * 平台
     */
    "platform": string;

    /**
     * 内核版本
     */
    "kernel_version": string;

    /**
     * 架构
     */
    "architecture": string;

    /**
     * 运行时间（秒）
     */
    "uptime_seconds": number;

    /**
     * 运行时间（可读）
     */
    "uptime_readable": string;

    /** Creates a new HostInfo instance. */
    constructor($$source: Partial<HostInfo> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("kernel_version" in $$source)) {
            this["kernel_version"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("uptime_seconds" in $$source)) {
            this["uptime_seconds"] = 0;
        }
        if (!("uptime_readable" in $$source)) {
            this["uptime_readable"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HostInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostInfo($$parsedSource as Partial<HostInfo>);
    }
}

/**
 * MemoryInfo 内存使用信息
 */
export class MemoryInfo {
    /**
     * 总内存（字节）
     */
    "total": string;

    /**
     * 已使用（字节）
     */
    "used": string;

    /**
     * 使用率（百分比）
     */
    "used_percent": number;

    /** Creates a new MemoryInfo instance. */
    constructor($$source: Partial<MemoryInfo> = {}) {
        if (!("total" in $$source)) {
            this["total"] = "";
        }
        if (!("used" in $$source)) {
            this["used"] = "";
        }
        if (!("used_percent" in $$source)) {
            this["used_percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryInfo($$parsedSource as Partial<MemoryInfo>);
    }
}

/**
 * NetworkInterface 网络接口信息
 */
export class NetworkInterface {
    /**
     * 接口名称
     */
    "name": string;

    /**
     * MAC 地址
     */
    "mac": string;

    /**
     * 最大传输单元
     */
    "mtu": number;

    /**
     * 是否启用
     */
    "isUp": boolean;

    /**
     * IPv4 地址
     */
    "ipv4": string;

    /**
     * IPv6 地址
     */
    "ipv6": string;

    /**
     * 发送字节数
     */
    "bytesSent": number;

    /**
     * 接收字节数
     */
    "bytesRecv": number;

    /**
     * 发送包数
     */
    "packetsSent": number;

    /**
     * 接收包数
     */
    "packetsRecv": number;

    /**
     * 每秒发送字节数
     */
    "bytesSentRate": number;

    /**
     * 每秒接收字节数
     */
    "bytesRecvRate": number;

    /**
     * 每秒发送包数
     */
    "packetsSentRate": number;

    /**
     * 每秒接收包数
     */
    "packetsRecvRate": number;

    /** Creates a new NetworkInterface instance. */
    constructor($$source: Partial<NetworkInterface> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mac" in $$source)) {
            this["mac"] = "";
        }
        if (!("mtu" in $$source)) {
            this["mtu"] = 0;
        }
        if (!("isUp" in $$source)) {
            this["isUp"] = false;
        }
        if (!("ipv4" in $$source)) {
            this["ipv4"] = "";
        }
        if (!("ipv6" in $$source)) {
            this["ipv6"] = "";
        }
        if (!("bytesSent" in $$source)) {
            this["bytesSent"] = 0;
        }
        if (!("bytesRecv" in $$source)) {
            this["bytesRecv"] = 0;
        }
        if (!("packetsSent" in $$source)) {
            this["packetsSent"] = 0;
        }
        if (!("packetsRecv" in $$source)) {
            this["packetsRecv"] = 0;
        }
        if (!("bytesSentRate" in $$source)) {
            this["bytesSentRate"] = 0;
        }
        if (!("bytesRecvRate" in $$source)) {
            this["bytesRecvRate"] = 0;
        }
        if (!("packetsSentRate" in $$source)) {
            this["packetsSentRate"] = 0;
        }
        if (!("packetsRecvRate" in $$source)) {
            this["packetsRecvRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInterface instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkInterface {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInterface($$parsedSource as Partial<NetworkInterface>);
    }
}

export class SysInfo {
    /**
     * 主机信息
     */
    "host_info": HostInfo | null;

    /**
     * CPU 使用率信息
     */
    "cpu_info": CPUInfo | null;

    /**
     * 内存使用信息
     */
    "memory_info": MemoryInfo | null;

    /**
     * 磁盘使用信息
     */
    "disk_info": DiskInfo | null;

    /**
     * 网络接口信息
     */
    "network_interfaces": NetworkInterface[];

    /** Creates a new SysInfo instance. */
    constructor($$source: Partial<SysInfo> = {}) {
        if (!("host_info" in $$source)) {
            this["host_info"] = null;
        }
        if (!("cpu_info" in $$source)) {
            this["cpu_info"] = null;
        }
        if (!("memory_info" in $$source)) {
            this["memory_info"] = null;
        }
        if (!("disk_info" in $$source)) {
            this["disk_info"] = null;
        }
        if (!("network_interfaces" in $$source)) {
            this["network_interfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SysInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SysInfo {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("host_info" in $$parsedSource) {
            $$parsedSource["host_info"] = $$createField0_0($$parsedSource["host_info"]);
        }
        if ("cpu_info" in $$parsedSource) {
            $$parsedSource["cpu_info"] = $$createField1_0($$parsedSource["cpu_info"]);
        }
        if ("memory_info" in $$parsedSource) {
            $$parsedSource["memory_info"] = $$createField2_0($$parsedSource["memory_info"]);
        }
        if ("disk_info" in $$parsedSource) {
            $$parsedSource["disk_info"] = $$createField3_0($$parsedSource["disk_info"]);
        }
        if ("network_interfaces" in $$parsedSource) {
            $$parsedSource["network_interfaces"] = $$createField4_0($$parsedSource["network_interfaces"]);
        }
        return new SysInfo($$parsedSource as Partial<SysInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = cpu$0.InfoStat.createFrom;
const $$createType2 = HostInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = CPUInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = MemoryInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = DiskInfo.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = NetworkInterface.createFrom;
const $$createType11 = $Create.Array($$createType10);
