// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SysInfoService 提供主机资源信息
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCPUInfo 获取 CPU 使用率信息（按核心）
 * @returns {Promise<$models.CPUInfo | null> & { cancel(): void }}
 */
export function GetCPUInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(682072826));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDiskInfo 获取根目录磁盘使用情况
 * @returns {Promise<$models.DiskInfo | null> & { cancel(): void }}
 */
export function GetDiskInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(1130086517));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetHostInfo 获取主机信息
 * @returns {Promise<$models.HostInfo | null> & { cancel(): void }}
 */
export function GetHostInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(4268509202));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetMemoryInfo 获取内存信息
 * @returns {Promise<$models.MemoryInfo | null> & { cancel(): void }}
 */
export function GetMemoryInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(3347101823));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType7($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetNetworkInterfaces 获取网络接口信息
 * @returns {Promise<$models.NetworkInterface[]> & { cancel(): void }}
 */
export function GetNetworkInterfaces() {
    let $resultPromise = /** @type {any} */($Call.ByID(2080101586));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType9($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetSysInfo 定时获取系统信息
 * @returns {Promise<$models.SysInfo | null> & { cancel(): void }}
 */
export function GetSysInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(239113));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType11($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.CPUInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DiskInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.HostInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.MemoryInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.NetworkInterface.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.SysInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
