// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ScanResult 检测结果
 */
export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("engine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engine"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

/**
 * StatsInfo 统计信息
 */
export class StatsInfo {
    /**
     * Creates a new StatsInfo instance.
     * @param {Partial<StatsInfo>} [$$source = {}] - The source object to create the StatsInfo.
     */
    constructor($$source = {}) {
        if (!("malicious" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["malicious"] = 0;
        }
        if (!("suspicious" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["suspicious"] = 0;
        }
        if (!("harmless" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["harmless"] = 0;
        }
        if (!("undetected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["undetected"] = 0;
        }
        if (!("typeUnsupported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["typeUnsupported"] = 0;
        }
        if (!("confirmedTimeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confirmedTimeout"] = 0;
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("failure" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failure"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsInfo(/** @type {Partial<StatsInfo>} */($$parsedSource));
    }
}

/**
 * VTFile 批量任务中的子文件
 */
export class VTFile {
    /**
     * Creates a new VTFile instance.
     * @param {Partial<VTFile>} [$$source = {}] - The source object to create the VTFile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            /**
             * 所属任务ID
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * pending/queued/completed/failed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analysisId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["completedAt"] = null;
        }
        if (!("md5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha1"] = "";
        }
        if (!("detectionRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detectionRate"] = 0;
        }
        if (!("totalEngines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalEngines"] = 0;
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {StatsInfo}
             */
            this["stats"] = (new StatsInfo());
        }
        if (!("results" in $$source)) {
            /**
             * 检测结果
             * @member
             * @type {ScanResult[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VTFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VTFile}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField14_0($$parsedSource["stats"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField15_0($$parsedSource["results"]);
        }
        return new VTFile(/** @type {Partial<VTFile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = StatsInfo.createFrom;
const $$createType1 = ScanResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
