// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ScanResult 检测结果
 */
export class ScanResult {
    "engine": string;
    "category": string;
    "result": string;
    "method": string;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

/**
 * StatsInfo 统计信息
 */
export class StatsInfo {
    "malicious": number;
    "suspicious": number;
    "harmless": number;
    "undetected": number;
    "typeUnsupported": number;
    "confirmedTimeout": number;
    "timeout": number;
    "failure": number;

    /** Creates a new StatsInfo instance. */
    constructor($$source: Partial<StatsInfo> = {}) {
        if (!("malicious" in $$source)) {
            this["malicious"] = 0;
        }
        if (!("suspicious" in $$source)) {
            this["suspicious"] = 0;
        }
        if (!("harmless" in $$source)) {
            this["harmless"] = 0;
        }
        if (!("undetected" in $$source)) {
            this["undetected"] = 0;
        }
        if (!("typeUnsupported" in $$source)) {
            this["typeUnsupported"] = 0;
        }
        if (!("confirmedTimeout" in $$source)) {
            this["confirmedTimeout"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("failure" in $$source)) {
            this["failure"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsInfo($$parsedSource as Partial<StatsInfo>);
    }
}

/**
 * VTFile 批量任务中的子文件
 */
export class VTFile {
    "id": string;

    /**
     * 所属任务ID
     */
    "taskId": string;
    "fileName": string;
    "filePath": string;
    "fileSize": number;

    /**
     * pending/queued/completed/failed
     */
    "status": string;
    "analysisId": string;
    "createdAt": time$0.Time;
    "completedAt": time$0.Time;
    "md5": string;
    "sha256": string;
    "sha1": string;
    "detectionRate": number;
    "totalEngines": number;
    "stats": StatsInfo;

    /**
     * 检测结果
     */
    "results": ScanResult[];

    /** Creates a new VTFile instance. */
    constructor($$source: Partial<VTFile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("analysisId" in $$source)) {
            this["analysisId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = null;
        }
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sha1" in $$source)) {
            this["sha1"] = "";
        }
        if (!("detectionRate" in $$source)) {
            this["detectionRate"] = 0;
        }
        if (!("totalEngines" in $$source)) {
            this["totalEngines"] = 0;
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new StatsInfo());
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VTFile instance from a string or object.
     */
    static createFrom($$source: any = {}): VTFile {
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField14_0($$parsedSource["stats"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField15_0($$parsedSource["results"]);
        }
        return new VTFile($$parsedSource as Partial<VTFile>);
    }
}

// Private type creation functions
const $$createType0 = StatsInfo.createFrom;
const $$createType1 = ScanResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
