// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("originalPath" in $$source)) {
            /**
             * 原始路径
             * @member
             * @type {string}
             */
            this["originalPath"] = "";
        }
        if (!("originalName" in $$source)) {
            /**
             * 原始文件名
             * @member
             * @type {string}
             */
            this["originalName"] = "";
        }
        if (!("newName" in $$source)) {
            /**
             * 新文件名
             * @member
             * @type {string}
             */
            this["newName"] = "";
        }
        if (!("newPath" in $$source)) {
            /**
             * 新文件路径
             * @member
             * @type {string}
             */
            this["newPath"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * 文件大小
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            /**
             * 是否是目录
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 错误信息
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * RenameResult 重命名结果
 */
export class RenameResult {
    /**
     * Creates a new RenameResult instance.
     * @param {Partial<RenameResult>} [$$source = {}] - The source object to create the RenameResult.
     */
    constructor($$source = {}) {
        if (!("successCount" in $$source)) {
            /**
             * 成功数量
             * @member
             * @type {number}
             */
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            /**
             * 失败数量
             * @member
             * @type {number}
             */
            this["failedCount"] = 0;
        }
        if (!("totalCount" in $$source)) {
            /**
             * 总数量
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * 重命名结果
             * @member
             * @type {FileInfo[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenameResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new RenameResult(/** @type {Partial<RenameResult>} */($$parsedSource));
    }
}

/**
 * RenameRule 重命名规则
 */
export class RenameRule {
    /**
     * Creates a new RenameRule instance.
     * @param {Partial<RenameRule>} [$$source = {}] - The source object to create the RenameRule.
     */
    constructor($$source = {}) {
        if (!("prefix" in $$source)) {
            /**
             * 前缀
             * @member
             * @type {string}
             */
            this["prefix"] = "";
        }
        if (!("suffix" in $$source)) {
            /**
             * 后缀
             * @member
             * @type {string}
             */
            this["suffix"] = "";
        }
        if (!("startNumber" in $$source)) {
            /**
             * 起始编号
             * @member
             * @type {number}
             */
            this["startNumber"] = 0;
        }
        if (!("numberDigits" in $$source)) {
            /**
             * 编号位数
             * @member
             * @type {number}
             */
            this["numberDigits"] = 0;
        }
        if (!("numberStep" in $$source)) {
            /**
             * 编号步长
             * @member
             * @type {number}
             */
            this["numberStep"] = 0;
        }
        if (!("replaceFrom" in $$source)) {
            /**
             * 要替换的文本
             * @member
             * @type {string}
             */
            this["replaceFrom"] = "";
        }
        if (!("replaceTo" in $$source)) {
            /**
             * 替换为的文本
             * @member
             * @type {string}
             */
            this["replaceTo"] = "";
        }
        if (!("caseSensitive" in $$source)) {
            /**
             * 是否区分大小写
             * @member
             * @type {boolean}
             */
            this["caseSensitive"] = false;
        }
        if (!("keepExtension" in $$source)) {
            /**
             * 是否保留扩展名
             * @member
             * @type {boolean}
             */
            this["keepExtension"] = false;
        }
        if (!("previewBeforeRename" in $$source)) {
            /**
             * 重命名前预览
             * @member
             * @type {boolean}
             */
            this["previewBeforeRename"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenameRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameRule(/** @type {Partial<RenameRule>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
