// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * 原始路径
     */
    "originalPath": string;

    /**
     * 原始文件名
     */
    "originalName": string;

    /**
     * 新文件名
     */
    "newName": string;

    /**
     * 新文件路径
     */
    "newPath": string;

    /**
     * 文件大小
     */
    "size": number;

    /**
     * 是否是目录
     */
    "isDir": boolean;

    /**
     * 错误信息
     */
    "error": string;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("originalPath" in $$source)) {
            this["originalPath"] = "";
        }
        if (!("originalName" in $$source)) {
            this["originalName"] = "";
        }
        if (!("newName" in $$source)) {
            this["newName"] = "";
        }
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * RenameResult 重命名结果
 */
export class RenameResult {
    /**
     * 成功数量
     */
    "successCount": number;

    /**
     * 失败数量
     */
    "failedCount": number;

    /**
     * 总数量
     */
    "totalCount": number;

    /**
     * 重命名结果
     */
    "results": FileInfo[];

    /** Creates a new RenameResult instance. */
    constructor($$source: Partial<RenameResult> = {}) {
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new RenameResult($$parsedSource as Partial<RenameResult>);
    }
}

/**
 * RenameRule 重命名规则
 */
export class RenameRule {
    /**
     * 前缀
     */
    "prefix": string;

    /**
     * 后缀
     */
    "suffix": string;

    /**
     * 起始编号
     */
    "startNumber": number;

    /**
     * 编号位数
     */
    "numberDigits": number;

    /**
     * 编号步长
     */
    "numberStep": number;

    /**
     * 要替换的文本
     */
    "replaceFrom": string;

    /**
     * 替换为的文本
     */
    "replaceTo": string;

    /**
     * 是否区分大小写
     */
    "caseSensitive": boolean;

    /**
     * 是否保留扩展名
     */
    "keepExtension": boolean;

    /**
     * 重命名前预览
     */
    "previewBeforeRename": boolean;

    /** Creates a new RenameRule instance. */
    constructor($$source: Partial<RenameRule> = {}) {
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("suffix" in $$source)) {
            this["suffix"] = "";
        }
        if (!("startNumber" in $$source)) {
            this["startNumber"] = 0;
        }
        if (!("numberDigits" in $$source)) {
            this["numberDigits"] = 0;
        }
        if (!("numberStep" in $$source)) {
            this["numberStep"] = 0;
        }
        if (!("replaceFrom" in $$source)) {
            this["replaceFrom"] = "";
        }
        if (!("replaceTo" in $$source)) {
            this["replaceTo"] = "";
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("keepExtension" in $$source)) {
            this["keepExtension"] = false;
        }
        if (!("previewBeforeRename" in $$source)) {
            this["previewBeforeRename"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameRule instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameRule($$parsedSource as Partial<RenameRule>);
    }
}

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
