// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RenameService 重命名服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchGetFileInfo 批量获取文件信息
 */
export function BatchGetFileInfo(filePaths: string[]): Promise<$models.FileInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3112040397, filePaths) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ExecuteRename 执行批量重命名
 */
export function ExecuteRename(files: $models.FileInfo[], rule: $models.RenameRule): Promise<$models.RenameResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2713528348, files, rule) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetFileInfo 获取文件信息
 */
export function GetFileInfo(filePath: string): Promise<$models.FileInfo | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1112127723, filePath) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenFileDialog 打开文件对话框并返回选中的文件路径
 */
export function OpenFileDialog(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2037445889) as any;
    return $resultPromise;
}

/**
 * OpenFileDialogs 打开文件对话框并返回选中的多个文件路径
 */
export function OpenFileDialogs(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2664587894) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * PreviewRename 预览重命名结果
 */
export function PreviewRename(files: $models.FileInfo[], rule: $models.RenameRule): Promise<$models.FileInfo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1405538759, files, rule) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ValidateRule 验证重命名规则
 */
export function ValidateRule(rule: $models.RenameRule): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4079511383, rule) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RenameResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Nullable($$createType0);
const $$createType5 = $Create.Array($Create.Any);
