// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RenameService 重命名服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchGetFileInfo 批量获取文件信息
 * @param {string[]} filePaths
 * @returns {Promise<$models.FileInfo[]> & { cancel(): void }}
 */
export function BatchGetFileInfo(filePaths) {
    let $resultPromise = /** @type {any} */($Call.ByID(3112040397, filePaths));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ExecuteRename 执行批量重命名
 * @param {$models.FileInfo[]} files
 * @param {$models.RenameRule} rule
 * @returns {Promise<$models.RenameResult | null> & { cancel(): void }}
 */
export function ExecuteRename(files, rule) {
    let $resultPromise = /** @type {any} */($Call.ByID(2713528348, files, rule));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetFileInfo 获取文件信息
 * @param {string} filePath
 * @returns {Promise<$models.FileInfo | null> & { cancel(): void }}
 */
export function GetFileInfo(filePath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1112127723, filePath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenFileDialog 打开文件对话框并返回选中的文件路径
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenFileDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(2037445889));
    return $resultPromise;
}

/**
 * OpenFileDialogs 打开文件对话框并返回选中的多个文件路径
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function OpenFileDialogs() {
    let $resultPromise = /** @type {any} */($Call.ByID(2664587894));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * PreviewRename 预览重命名结果
 * @param {$models.FileInfo[]} files
 * @param {$models.RenameRule} rule
 * @returns {Promise<$models.FileInfo[]> & { cancel(): void }}
 */
export function PreviewRename(files, rule) {
    let $resultPromise = /** @type {any} */($Call.ByID(1405538759, files, rule));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ValidateRule 验证重命名规则
 * @param {$models.RenameRule} rule
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ValidateRule(rule) {
    let $resultPromise = /** @type {any} */($Call.ByID(4079511383, rule));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RenameResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Nullable($$createType0);
const $$createType5 = $Create.Array($Create.Any);
