// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ByteConversionResult 字节转换结果
 */
export class ByteConversionResult {
    /**
     * Creates a new ByteConversionResult instance.
     * @param {Partial<ByteConversionResult>} [$$source = {}] - The source object to create the ByteConversionResult.
     */
    constructor($$source = {}) {
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("kilobytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["kilobytes"] = 0;
        }
        if (!("megabytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["megabytes"] = 0;
        }
        if (!("gigabytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gigabytes"] = 0;
        }
        if (!("terabytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["terabytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ByteConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ByteConversionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ByteConversionResult(/** @type {Partial<ByteConversionResult>} */($$parsedSource));
    }
}

/**
 * LengthConversionResult 长度转换结果
 */
export class LengthConversionResult {
    /**
     * Creates a new LengthConversionResult instance.
     * @param {Partial<LengthConversionResult>} [$$source = {}] - The source object to create the LengthConversionResult.
     */
    constructor($$source = {}) {
        if (!("millimeters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["millimeters"] = 0;
        }
        if (!("centimeters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["centimeters"] = 0;
        }
        if (!("meters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["meters"] = 0;
        }
        if (!("kilometers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["kilometers"] = 0;
        }
        if (!("inches" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inches"] = 0;
        }
        if (!("feet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feet"] = 0;
        }
        if (!("yards" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["yards"] = 0;
        }
        if (!("miles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["miles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LengthConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LengthConversionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LengthConversionResult(/** @type {Partial<LengthConversionResult>} */($$parsedSource));
    }
}

/**
 * TimeConversionResult 时间转换结果
 */
export class TimeConversionResult {
    /**
     * Creates a new TimeConversionResult instance.
     * @param {Partial<TimeConversionResult>} [$$source = {}] - The source object to create the TimeConversionResult.
     */
    constructor($$source = {}) {
        if (!("milliseconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["milliseconds"] = 0;
        }
        if (!("seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seconds"] = 0;
        }
        if (!("minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minutes"] = 0;
        }
        if (!("hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }
        if (!("days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["days"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weeks"] = 0;
        }
        if (!("months" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["months"] = 0;
        }
        if (!("years" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["years"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeConversionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeConversionResult(/** @type {Partial<TimeConversionResult>} */($$parsedSource));
    }
}
