// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ByteConversionResult 字节转换结果
 */
export class ByteConversionResult {
    "bytes": number;
    "kilobytes": number;
    "megabytes": number;
    "gigabytes": number;
    "terabytes": number;

    /** Creates a new ByteConversionResult instance. */
    constructor($$source: Partial<ByteConversionResult> = {}) {
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("kilobytes" in $$source)) {
            this["kilobytes"] = 0;
        }
        if (!("megabytes" in $$source)) {
            this["megabytes"] = 0;
        }
        if (!("gigabytes" in $$source)) {
            this["gigabytes"] = 0;
        }
        if (!("terabytes" in $$source)) {
            this["terabytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ByteConversionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ByteConversionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ByteConversionResult($$parsedSource as Partial<ByteConversionResult>);
    }
}

/**
 * LengthConversionResult 长度转换结果
 */
export class LengthConversionResult {
    "millimeters": number;
    "centimeters": number;
    "meters": number;
    "kilometers": number;
    "inches": number;
    "feet": number;
    "yards": number;
    "miles": number;

    /** Creates a new LengthConversionResult instance. */
    constructor($$source: Partial<LengthConversionResult> = {}) {
        if (!("millimeters" in $$source)) {
            this["millimeters"] = 0;
        }
        if (!("centimeters" in $$source)) {
            this["centimeters"] = 0;
        }
        if (!("meters" in $$source)) {
            this["meters"] = 0;
        }
        if (!("kilometers" in $$source)) {
            this["kilometers"] = 0;
        }
        if (!("inches" in $$source)) {
            this["inches"] = 0;
        }
        if (!("feet" in $$source)) {
            this["feet"] = 0;
        }
        if (!("yards" in $$source)) {
            this["yards"] = 0;
        }
        if (!("miles" in $$source)) {
            this["miles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LengthConversionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LengthConversionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LengthConversionResult($$parsedSource as Partial<LengthConversionResult>);
    }
}

/**
 * TimeConversionResult 时间转换结果
 */
export class TimeConversionResult {
    "milliseconds": number;
    "seconds": number;
    "minutes": number;
    "hours": number;
    "days": number;
    "weeks": number;
    "months": number;
    "years": number;

    /** Creates a new TimeConversionResult instance. */
    constructor($$source: Partial<TimeConversionResult> = {}) {
        if (!("milliseconds" in $$source)) {
            this["milliseconds"] = 0;
        }
        if (!("seconds" in $$source)) {
            this["seconds"] = 0;
        }
        if (!("minutes" in $$source)) {
            this["minutes"] = 0;
        }
        if (!("hours" in $$source)) {
            this["hours"] = 0;
        }
        if (!("days" in $$source)) {
            this["days"] = 0;
        }
        if (!("weeks" in $$source)) {
            this["weeks"] = 0;
        }
        if (!("months" in $$source)) {
            this["months"] = 0;
        }
        if (!("years" in $$source)) {
            this["years"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeConversionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeConversionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeConversionResult($$parsedSource as Partial<TimeConversionResult>);
    }
}
