// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UnitConverterService 单位转换服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConvertBytes 字节转换
 * unit: "B", "KB", "MB", "GB", "TB"
 */
export function ConvertBytes(value: number, unit: string): Promise<$models.ByteConversionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2861254849, value, unit) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ConvertLength 长度转换
 * unit: "mm", "cm", "m", "km", "in", "ft", "yd", "mi"
 */
export function ConvertLength(value: number, unit: string): Promise<$models.LengthConversionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1175811510, value, unit) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ConvertTime 时间转换
 * unit: "ms", "s", "min", "h", "d", "w", "mon", "y"
 */
export function ConvertTime(value: number, unit: string): Promise<$models.TimeConversionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1939060803, value, unit) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ByteConversionResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LengthConversionResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.TimeConversionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
