// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除日报
 */
export function Delete(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2789805048, id) as any;
    return $resultPromise;
}

/**
 * Get 获取指定日期的日报
 */
export function Get(date: string): Promise<$models.DailyReport | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3776535301, date) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAll 获取所有日报 (分页)
 */
export function GetAll(limit: number, offset: number): Promise<[$models.DailyReport[], number]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3374758052, limit, offset) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetRange 获取日期范围内的日报
 */
export function GetRange(startDate: string, endDate: string): Promise<$models.DailyReport[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(381753266, startDate, endDate) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetStats 获取日报统计
 */
export function GetStats(): Promise<$models.DailyReportStats | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1783461580) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Save 保存日报 (创建或更新)
 */
export function Save(date: string, content: string, summary: string, tags: string[]): Promise<$models.DailyReport | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1720672358, date, content, summary, tags) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.DailyReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.DailyReportStats.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
