// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除日报
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Delete(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(2789805048, id));
    return $resultPromise;
}

/**
 * Get 获取指定日期的日报
 * @param {string} date
 * @returns {Promise<$models.DailyReport | null> & { cancel(): void }}
 */
export function Get(date) {
    let $resultPromise = /** @type {any} */($Call.ByID(3776535301, date));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAll 获取所有日报 (分页)
 * @param {number} limit
 * @param {number} offset
 * @returns {Promise<[$models.DailyReport[], number]> & { cancel(): void }}
 */
export function GetAll(limit, offset) {
    let $resultPromise = /** @type {any} */($Call.ByID(3374758052, limit, offset));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetRange 获取日期范围内的日报
 * @param {string} startDate
 * @param {string} endDate
 * @returns {Promise<$models.DailyReport[]> & { cancel(): void }}
 */
export function GetRange(startDate, endDate) {
    let $resultPromise = /** @type {any} */($Call.ByID(381753266, startDate, endDate));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetStats 获取日报统计
 * @returns {Promise<$models.DailyReportStats | null> & { cancel(): void }}
 */
export function GetStats() {
    let $resultPromise = /** @type {any} */($Call.ByID(1783461580));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Save 保存日报 (创建或更新)
 * @param {string} date
 * @param {string} content
 * @param {string} summary
 * @param {string[]} tags
 * @returns {Promise<$models.DailyReport | null> & { cancel(): void }}
 */
export function Save(date, content, summary, tags) {
    let $resultPromise = /** @type {any} */($Call.ByID(1720672358, date, content, summary, tags));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.DailyReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.DailyReportStats.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
