// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DailyReportService from "./dailyreportservice.js";
export {
    DailyReportService
};

export * from "./models.js";
