// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class DailyReport {
    "id": number;
    "date": string;
    "content": string;
    "summary": string;
    "tags": string[];

    /** Creates a new DailyReport instance. */
    constructor($$source: Partial<DailyReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReport instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyReport {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new DailyReport($$parsedSource as Partial<DailyReport>);
    }
}

export class DailyReportStats {
    "total_reports": number;
    "current_streak": number;
    "longest_streak": number;

    /** Creates a new DailyReportStats instance. */
    constructor($$source: Partial<DailyReportStats> = {}) {
        if (!("total_reports" in $$source)) {
            this["total_reports"] = 0;
        }
        if (!("current_streak" in $$source)) {
            this["current_streak"] = 0;
        }
        if (!("longest_streak" in $$source)) {
            this["longest_streak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReportStats instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyReportStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyReportStats($$parsedSource as Partial<DailyReportStats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
