// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class DailyReport {
    /**
     * Creates a new DailyReport instance.
     * @param {Partial<DailyReport>} [$$source = {}] - The source object to create the DailyReport.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyReport}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new DailyReport(/** @type {Partial<DailyReport>} */($$parsedSource));
    }
}

export class DailyReportStats {
    /**
     * Creates a new DailyReportStats instance.
     * @param {Partial<DailyReportStats>} [$$source = {}] - The source object to create the DailyReportStats.
     */
    constructor($$source = {}) {
        if (!("total_reports" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_reports"] = 0;
        }
        if (!("current_streak" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current_streak"] = 0;
        }
        if (!("longest_streak" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["longest_streak"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyReportStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyReportStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyReportStats(/** @type {Partial<DailyReportStats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
