// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 剪贴板服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetText 获取剪贴板文本
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetText() {
    let $resultPromise = /** @type {any} */($Call.ByID(1578442778));
    return $resultPromise;
}

/**
 * SetText 设置剪贴板文本
 * @param {string} text
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function SetText(text) {
    let $resultPromise = /** @type {any} */($Call.ByID(821063710, text));
    return $resultPromise;
}
