// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 剪贴板服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetText 获取剪贴板文本
 */
export function GetText(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1578442778) as any;
    return $resultPromise;
}

/**
 * SetText 设置剪贴板文本
 */
export function SetText(text: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(821063710, text) as any;
    return $resultPromise;
}
