// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetLastUsedTime 获取上次使用时间
 */
export function GetLastUsedTime(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1764847793) as any;
    return $resultPromise;
}

/**
 * GetLastUsedTimestamp 获取上次使用时间戳（秒）
 */
export function GetLastUsedTimestamp(): Promise<number | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3892126408) as any;
    return $resultPromise;
}

/**
 * UpdateLastUsedTime 更新上次使用时间
 */
export function UpdateLastUsedTime(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2439002090) as any;
    return $resultPromise;
}
