// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * GetLastUsedTime 获取上次使用时间
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetLastUsedTime() {
    let $resultPromise = /** @type {any} */($Call.ByID(1764847793));
    return $resultPromise;
}

/**
 * GetLastUsedTimestamp 获取上次使用时间戳（秒）
 * @returns {Promise<number | null> & { cancel(): void }}
 */
export function GetLastUsedTimestamp() {
    let $resultPromise = /** @type {any} */($Call.ByID(3892126408));
    return $resultPromise;
}

/**
 * UpdateLastUsedTime 更新上次使用时间
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateLastUsedTime() {
    let $resultPromise = /** @type {any} */($Call.ByID(2439002090));
    return $resultPromise;
}
