// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EncryptionService 加密工具服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Base64Decode Base64 解码
 */
export function Base64Decode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1166816400, input) as any;
    return $resultPromise;
}

/**
 * Base64Encode Base64 编码
 */
export function Base64Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2027023524, input) as any;
    return $resultPromise;
}

/**
 * Base64URLDecode Base64 URL 解码
 */
export function Base64URLDecode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(410895793, input) as any;
    return $resultPromise;
}

/**
 * Base64URLEncode Base64 URL 编码
 */
export function Base64URLEncode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1153188589, input) as any;
    return $resultPromise;
}

/**
 * BatchEncode 批量编码（一次性生成所有哈希值）
 */
export function BatchEncode(input: string): Promise<$models.BatchEncodeResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1127860149, input) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * HexToUTF8 十六进制转 UTF-8 字符串
 */
export function HexToUTF8(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(608302492, input) as any;
    return $resultPromise;
}

/**
 * MD5Encode MD5 编码
 */
export function MD5Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(952701309, input) as any;
    return $resultPromise;
}

/**
 * MD5EncodeBytes MD5 编码（字节数组）
 */
export function MD5EncodeBytes(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(324362652, input) as any;
    return $resultPromise;
}

/**
 * SHA1Encode SHA1 编码
 */
export function SHA1Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(443017458, input) as any;
    return $resultPromise;
}

/**
 * SHA1EncodeBytes SHA1 编码（字节数组）
 */
export function SHA1EncodeBytes(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2605921713, input) as any;
    return $resultPromise;
}

/**
 * SHA256Encode SHA256 编码
 */
export function SHA256Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2593897036, input) as any;
    return $resultPromise;
}

/**
 * SHA256EncodeBytes SHA256 编码（字节数组）
 */
export function SHA256EncodeBytes(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2075046959, input) as any;
    return $resultPromise;
}

/**
 * SHA512Encode SHA512 编码
 */
export function SHA512Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(173317469, input) as any;
    return $resultPromise;
}

/**
 * SHA512EncodeBytes SHA512 编码（字节数组）
 */
export function SHA512EncodeBytes(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1580234556, input) as any;
    return $resultPromise;
}

/**
 * UTF8Decode UTF-8 解码（将 UTF-8 字节转换为字符串）
 */
export function UTF8Decode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1436703720, input) as any;
    return $resultPromise;
}

/**
 * UTF8Encode UTF-8 编码（将字符串转换为 UTF-8 字节表示）
 */
export function UTF8Encode(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2454474956, input) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $Create.ByteSlice($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * UTF8ToHex UTF-8 字符串转十六进制
 */
export function UTF8ToHex(input: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(779156892, input) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.BatchEncodeResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
