// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EncryptionService 加密工具服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Base64Decode Base64 解码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Base64Decode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(1166816400, input));
    return $resultPromise;
}

/**
 * Base64Encode Base64 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Base64Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(2027023524, input));
    return $resultPromise;
}

/**
 * Base64URLDecode Base64 URL 解码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Base64URLDecode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(410895793, input));
    return $resultPromise;
}

/**
 * Base64URLEncode Base64 URL 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Base64URLEncode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(1153188589, input));
    return $resultPromise;
}

/**
 * BatchEncode 批量编码（一次性生成所有哈希值）
 * @param {string} input
 * @returns {Promise<$models.BatchEncodeResult | null> & { cancel(): void }}
 */
export function BatchEncode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(1127860149, input));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * HexToUTF8 十六进制转 UTF-8 字符串
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function HexToUTF8(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(608302492, input));
    return $resultPromise;
}

/**
 * MD5Encode MD5 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function MD5Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(952701309, input));
    return $resultPromise;
}

/**
 * MD5EncodeBytes MD5 编码（字节数组）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function MD5EncodeBytes(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(324362652, input));
    return $resultPromise;
}

/**
 * SHA1Encode SHA1 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA1Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(443017458, input));
    return $resultPromise;
}

/**
 * SHA1EncodeBytes SHA1 编码（字节数组）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA1EncodeBytes(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(2605921713, input));
    return $resultPromise;
}

/**
 * SHA256Encode SHA256 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA256Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(2593897036, input));
    return $resultPromise;
}

/**
 * SHA256EncodeBytes SHA256 编码（字节数组）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA256EncodeBytes(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(2075046959, input));
    return $resultPromise;
}

/**
 * SHA512Encode SHA512 编码
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA512Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(173317469, input));
    return $resultPromise;
}

/**
 * SHA512EncodeBytes SHA512 编码（字节数组）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function SHA512EncodeBytes(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(1580234556, input));
    return $resultPromise;
}

/**
 * UTF8Decode UTF-8 解码（将 UTF-8 字节转换为字符串）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function UTF8Decode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(1436703720, input));
    return $resultPromise;
}

/**
 * UTF8Encode UTF-8 编码（将字符串转换为 UTF-8 字节表示）
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function UTF8Encode(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(2454474956, input));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $Create.ByteSlice($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * UTF8ToHex UTF-8 字符串转十六进制
 * @param {string} input
 * @returns {Promise<string> & { cancel(): void }}
 */
export function UTF8ToHex(input) {
    let $resultPromise = /** @type {any} */($Call.ByID(779156892, input));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.BatchEncodeResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
