// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * BatchEncodeResult 批量编码结果
 */
export class BatchEncodeResult {
    "md5": string;
    "sha1": string;
    "sha256": string;
    "sha512": string;
    "base64": string;

    /** Creates a new BatchEncodeResult instance. */
    constructor($$source: Partial<BatchEncodeResult> = {}) {
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("sha1" in $$source)) {
            this["sha1"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sha512" in $$source)) {
            this["sha512"] = "";
        }
        if (!("base64" in $$source)) {
            this["base64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchEncodeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchEncodeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchEncodeResult($$parsedSource as Partial<BatchEncodeResult>);
    }
}
