// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Todo {
    "id": number;
    "title": string;
    "completed": boolean;
    "category_id": number | null;
    "due_date": string | null;
    "priority": number;
    "status": number;

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }
        if (!("category_id" in $$source)) {
            this["category_id"] = null;
        }
        if (!("due_date" in $$source)) {
            this["due_date"] = null;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Todo($$parsedSource as Partial<Todo>);
    }
}
