// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Todo {
    /**
     * Creates a new Todo instance.
     * @param {Partial<Todo>} [$$source = {}] - The source object to create the Todo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("category_id" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["category_id"] = null;
        }
        if (!("due_date" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["due_date"] = null;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Todo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Todo(/** @type {Partial<Todo>} */($$parsedSource));
    }
}
