// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(title: string, categoryID: number | null, dueDate: string | null, priority: number): Promise<$models.Todo | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1284602110, title, categoryID, dueDate, priority) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Delete(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3552139800, id) as any;
    return $resultPromise;
}

export function GetAll(): Promise<$models.Todo[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2978239364) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Toggle(id: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3974504335, id) as any;
    return $resultPromise;
}

export function Update(id: number, title: string, completed: boolean, categoryID: number | null, dueDate: string | null, priority: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2202805994, id, title, completed, categoryID, dueDate, priority) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Todo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
