// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} title
 * @param {number | null} categoryID
 * @param {string | null} dueDate
 * @param {number} priority
 * @returns {Promise<$models.Todo | null> & { cancel(): void }}
 */
export function Add(title, categoryID, dueDate, priority) {
    let $resultPromise = /** @type {any} */($Call.ByID(1284602110, title, categoryID, dueDate, priority));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Delete(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(3552139800, id));
    return $resultPromise;
}

/**
 * @returns {Promise<$models.Todo[]> & { cancel(): void }}
 */
export function GetAll() {
    let $resultPromise = /** @type {any} */($Call.ByID(2978239364));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Toggle(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(3974504335, id));
    return $resultPromise;
}

/**
 * @param {number} id
 * @param {string} title
 * @param {boolean} completed
 * @param {number | null} categoryID
 * @param {string | null} dueDate
 * @param {number} priority
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Update(id, title, completed, categoryID, dueDate, priority) {
    let $resultPromise = /** @type {any} */($Call.ByID(2202805994, id, title, completed, categoryID, dueDate, priority));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Todo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
