// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DNSService DNS服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FlushDNS 刷新DNS缓存
 * @returns {Promise<$models.DNSFlushResult | null> & { cancel(): void }}
 */
export function FlushDNS() {
    let $resultPromise = /** @type {any} */($Call.ByID(943109919));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetDNSInfo 获取DNS信息
 * @returns {Promise<{ [_: string]: any }> & { cancel(): void }}
 */
export function GetDNSInfo() {
    let $resultPromise = /** @type {any} */($Call.ByID(3574554813));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SetApp 设置应用实例
 * @param {application$0.App | null} app
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetApp(app) {
    let $resultPromise = /** @type {any} */($Call.ByID(1052153997, app));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.DNSFlushResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
