// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileTransferService 文件传输服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CountFilesInDirectory 统计目录中的文件数量
 * @param {string} dirPath
 * @returns {Promise<number> & { cancel(): void }}
 */
export function CountFilesInDirectory(dirPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(316075000, dirPath));
    return $resultPromise;
}

/**
 * DownloadFile 下载文件 (模拟)
 * @param {string} remotePath
 * @param {string} localPath
 * @param {string} protocol
 * @returns {Promise<$models.TransferResult | null> & { cancel(): void }}
 */
export function DownloadFile(remotePath, localPath, protocol) {
    let $resultPromise = /** @type {any} */($Call.ByID(2225373042, remotePath, localPath, protocol));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ListLocalFiles 列出本地目录文件
 * @param {string} dirPath
 * @returns {Promise<$models.FileListResult | null> & { cancel(): void }}
 */
export function ListLocalFiles(dirPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1347316694, dirPath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenDirectoryDialog 打开目录对话框
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenDirectoryDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(615492867));
    return $resultPromise;
}

/**
 * OpenFileDialog 打开文件对话框
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenFileDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(1944423194));
    return $resultPromise;
}

/**
 * TestFTPConnection 测试FTP连接
 * @param {$models.FTPConfig} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestFTPConnection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(3773728778, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestS3Connection 测试S3连接
 * @param {$models.S3Config} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestS3Connection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(800546498, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestSFTPConnection 测试SFTP连接
 * @param {$models.SFTPConfig} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestSFTPConnection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(2784210613, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestSMBConnection 测试SMB连接
 * @param {$models.SMBConfig} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestSMBConnection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(923096870, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * UploadFile 上传文件 (模拟)
 * @param {string} localPath
 * @param {string} remotePath
 * @param {string} protocol
 * @returns {Promise<$models.TransferResult | null> & { cancel(): void }}
 */
export function UploadFile(localPath, remotePath, protocol) {
    let $resultPromise = /** @type {any} */($Call.ByID(472521211, localPath, remotePath, protocol));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.TransferResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileListResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ConnectionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
