// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileTransferService 文件传输服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CountFilesInDirectory 统计目录中的文件数量
 */
export function CountFilesInDirectory(dirPath: string): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(316075000, dirPath) as any;
    return $resultPromise;
}

/**
 * DownloadFile 下载文件 (模拟)
 */
export function DownloadFile(remotePath: string, localPath: string, protocol: string): Promise<$models.TransferResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2225373042, remotePath, localPath, protocol) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ListLocalFiles 列出本地目录文件
 */
export function ListLocalFiles(dirPath: string): Promise<$models.FileListResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1347316694, dirPath) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * OpenDirectoryDialog 打开目录对话框
 */
export function OpenDirectoryDialog(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(615492867) as any;
    return $resultPromise;
}

/**
 * OpenFileDialog 打开文件对话框
 */
export function OpenFileDialog(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1944423194) as any;
    return $resultPromise;
}

/**
 * TestFTPConnection 测试FTP连接
 */
export function TestFTPConnection(config: $models.FTPConfig): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3773728778, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestS3Connection 测试S3连接
 */
export function TestS3Connection(config: $models.S3Config): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(800546498, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestSFTPConnection 测试SFTP连接
 */
export function TestSFTPConnection(config: $models.SFTPConfig): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2784210613, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestSMBConnection 测试SMB连接
 */
export function TestSMBConnection(config: $models.SMBConfig): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(923096870, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * UploadFile 上传文件 (模拟)
 */
export function UploadFile(localPath: string, remotePath: string, protocol: string): Promise<$models.TransferResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(472521211, localPath, remotePath, protocol) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.TransferResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileListResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ConnectionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
