// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DNSService from "./dnsservice.js";
import * as FileTransferService from "./filetransferservice.js";
import * as TCPUDPService from "./tcpudpservice.js";
export {
    DNSService,
    FileTransferService,
    TCPUDPService
};

export * from "./models.js";
