// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ConnectionResult 连接结果
 */
export class ConnectionResult {
    /**
     * Creates a new ConnectionResult instance.
     * @param {Partial<ConnectionResult>} [$$source = {}] - The source object to create the ConnectionResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * 是否成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * 延迟(毫秒)
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionResult(/** @type {Partial<ConnectionResult>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus 连接状态
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("isConnected" in $$source)) {
            /**
             * 是否已连接
             * @member
             * @type {boolean}
             */
            this["isConnected"] = false;
        }
        if (!("localAddr" in $$source)) {
            /**
             * 本地地址
             * @member
             * @type {string}
             */
            this["localAddr"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            /**
             * 远程地址
             * @member
             * @type {string}
             */
            this["remoteAddr"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * 协议类型
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * 模式: client/server
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("serverRunning" in $$source)) {
            /**
             * 服务端是否运行
             * @member
             * @type {boolean}
             */
            this["serverRunning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * DNSFlushResult DNS刷新结果
 */
export class DNSFlushResult {
    /**
     * Creates a new DNSFlushResult instance.
     * @param {Partial<DNSFlushResult>} [$$source = {}] - The source object to create the DNSFlushResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * 是否成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * 命令输出
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("adminNeeded" in $$source)) {
            /**
             * 是否需要管理员权限
             * @member
             * @type {boolean}
             */
            this["adminNeeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSFlushResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSFlushResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSFlushResult(/** @type {Partial<DNSFlushResult>} */($$parsedSource));
    }
}

/**
 * FTPConfig FTP配置
 */
export class FTPConfig {
    /**
     * Creates a new FTPConfig instance.
     * @param {Partial<FTPConfig>} [$$source = {}] - The source object to create the FTPConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * 主机地址
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * 用户名
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * 密码
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * 超时时间(秒)
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FTPConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FTPConfig(/** @type {Partial<FTPConfig>} */($$parsedSource));
    }
}

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 文件名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * 大小
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            /**
             * 是否是目录
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * FileListResult 文件列表结果
 */
export class FileListResult {
    /**
     * Creates a new FileListResult instance.
     * @param {Partial<FileListResult>} [$$source = {}] - The source object to create the FileListResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * 是否成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * 文件列表
             * @member
             * @type {FileInfo[]}
             */
            this["files"] = [];
        }
        if (!("count" in $$source)) {
            /**
             * 文件数量
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileListResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        return new FileListResult(/** @type {Partial<FileListResult>} */($$parsedSource));
    }
}

/**
 * MessageResult 消息结果
 */
export class MessageResult {
    /**
     * Creates a new MessageResult instance.
     * @param {Partial<MessageResult>} [$$source = {}] - The source object to create the MessageResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * 是否成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * 数据
             * @member
             * @type {string}
             */
            this["data"] = "";
        }
        if (!("hexData" in $$source)) {
            /**
             * 十六进制数据
             * @member
             * @type {string}
             */
            this["hexData"] = "";
        }
        if (!("length" in $$source)) {
            /**
             * 数据长度
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageResult(/** @type {Partial<MessageResult>} */($$parsedSource));
    }
}

/**
 * S3Config S3配置
 */
export class S3Config {
    /**
     * Creates a new S3Config instance.
     * @param {Partial<S3Config>} [$$source = {}] - The source object to create the S3Config.
     */
    constructor($$source = {}) {
        if (!("endpoint" in $$source)) {
            /**
             * 端点URL
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("accessKeyId" in $$source)) {
            /**
             * 访问密钥ID
             * @member
             * @type {string}
             */
            this["accessKeyId"] = "";
        }
        if (!("secretAccessKey" in $$source)) {
            /**
             * 秘密访问密钥
             * @member
             * @type {string}
             */
            this["secretAccessKey"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * 区域
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("bucket" in $$source)) {
            /**
             * 存储桶名称
             * @member
             * @type {string}
             */
            this["bucket"] = "";
        }
        if (!("useSSL" in $$source)) {
            /**
             * 是否使用SSL
             * @member
             * @type {boolean}
             */
            this["useSSL"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new S3Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {S3Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new S3Config(/** @type {Partial<S3Config>} */($$parsedSource));
    }
}

/**
 * SFTPConfig SFTP配置
 */
export class SFTPConfig {
    /**
     * Creates a new SFTPConfig instance.
     * @param {Partial<SFTPConfig>} [$$source = {}] - The source object to create the SFTPConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * 主机地址
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * 用户名
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * 密码
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("keyFile" in $$source)) {
            /**
             * SSH私钥文件路径
             * @member
             * @type {string}
             */
            this["keyFile"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * 超时时间(秒)
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPConfig(/** @type {Partial<SFTPConfig>} */($$parsedSource));
    }
}

/**
 * SMBConfig SMB配置
 */
export class SMBConfig {
    /**
     * Creates a new SMBConfig instance.
     * @param {Partial<SMBConfig>} [$$source = {}] - The source object to create the SMBConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * 主机地址
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * 用户名
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * 密码
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("share" in $$source)) {
            /**
             * 共享名称
             * @member
             * @type {string}
             */
            this["share"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * 超时时间(秒)
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMBConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SMBConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMBConfig(/** @type {Partial<SMBConfig>} */($$parsedSource));
    }
}

/**
 * TCPUDPConfig TCP/UDP配置
 */
export class TCPUDPConfig {
    /**
     * Creates a new TCPUDPConfig instance.
     * @param {Partial<TCPUDPConfig>} [$$source = {}] - The source object to create the TCPUDPConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * 主机地址
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 端口
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("timeout" in $$source)) {
            /**
             * 超时时间(秒)
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TCPUDPConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TCPUDPConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TCPUDPConfig(/** @type {Partial<TCPUDPConfig>} */($$parsedSource));
    }
}

/**
 * TransferResult 传输结果
 */
export class TransferResult {
    /**
     * Creates a new TransferResult instance.
     * @param {Partial<TransferResult>} [$$source = {}] - The source object to create the TransferResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * 是否成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * 传输字节数
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("time" in $$source)) {
            /**
             * 耗时(毫秒)
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * 速度
             * @member
             * @type {string}
             */
            this["speed"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * 本地路径
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("remotePath" in $$source)) {
            /**
             * 远程路径
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransferResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferResult(/** @type {Partial<TransferResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
