// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ConnectionResult 连接结果
 */
export class ConnectionResult {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 消息
     */
    "message": string;

    /**
     * 延迟(毫秒)
     */
    "latency": number;

    /** Creates a new ConnectionResult instance. */
    constructor($$source: Partial<ConnectionResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("latency" in $$source)) {
            this["latency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionResult($$parsedSource as Partial<ConnectionResult>);
    }
}

/**
 * ConnectionStatus 连接状态
 */
export class ConnectionStatus {
    /**
     * 是否已连接
     */
    "isConnected": boolean;

    /**
     * 本地地址
     */
    "localAddr": string;

    /**
     * 远程地址
     */
    "remoteAddr": string;

    /**
     * 协议类型
     */
    "protocol": string;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("isConnected" in $$source)) {
            this["isConnected"] = false;
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

/**
 * FTPConfig FTP配置
 */
export class FTPConfig {
    /**
     * 主机地址
     */
    "host": string;

    /**
     * 端口
     */
    "port": number;

    /**
     * 用户名
     */
    "username": string;

    /**
     * 密码
     */
    "password": string;

    /**
     * 超时时间(秒)
     */
    "timeout": number;

    /** Creates a new FTPConfig instance. */
    constructor($$source: Partial<FTPConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FTPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FTPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FTPConfig($$parsedSource as Partial<FTPConfig>);
    }
}

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * 文件名
     */
    "name": string;

    /**
     * 路径
     */
    "path": string;

    /**
     * 大小
     */
    "size": number;

    /**
     * 是否是目录
     */
    "isDir": boolean;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * FileListResult 文件列表结果
 */
export class FileListResult {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 消息
     */
    "message": string;

    /**
     * 文件列表
     */
    "files": FileInfo[];

    /**
     * 文件数量
     */
    "count": number;

    /** Creates a new FileListResult instance. */
    constructor($$source: Partial<FileListResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileListResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        return new FileListResult($$parsedSource as Partial<FileListResult>);
    }
}

/**
 * MessageResult 消息结果
 */
export class MessageResult {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 消息
     */
    "message": string;

    /**
     * 数据
     */
    "data": string;

    /**
     * 十六进制数据
     */
    "hexData": string;

    /**
     * 数据长度
     */
    "length": number;

    /** Creates a new MessageResult instance. */
    constructor($$source: Partial<MessageResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("hexData" in $$source)) {
            this["hexData"] = "";
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageResult($$parsedSource as Partial<MessageResult>);
    }
}

/**
 * S3Config S3配置
 */
export class S3Config {
    /**
     * 端点URL
     */
    "endpoint": string;

    /**
     * 访问密钥ID
     */
    "accessKeyId": string;

    /**
     * 秘密访问密钥
     */
    "secretAccessKey": string;

    /**
     * 区域
     */
    "region": string;

    /**
     * 存储桶名称
     */
    "bucket": string;

    /**
     * 是否使用SSL
     */
    "useSSL": boolean;

    /** Creates a new S3Config instance. */
    constructor($$source: Partial<S3Config> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("accessKeyId" in $$source)) {
            this["accessKeyId"] = "";
        }
        if (!("secretAccessKey" in $$source)) {
            this["secretAccessKey"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("useSSL" in $$source)) {
            this["useSSL"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new S3Config instance from a string or object.
     */
    static createFrom($$source: any = {}): S3Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new S3Config($$parsedSource as Partial<S3Config>);
    }
}

/**
 * SFTPConfig SFTP配置
 */
export class SFTPConfig {
    /**
     * 主机地址
     */
    "host": string;

    /**
     * 端口
     */
    "port": number;

    /**
     * 用户名
     */
    "username": string;

    /**
     * 密码
     */
    "password": string;

    /**
     * SSH私钥文件路径
     */
    "keyFile": string;

    /**
     * 超时时间(秒)
     */
    "timeout": number;

    /** Creates a new SFTPConfig instance. */
    constructor($$source: Partial<SFTPConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("keyFile" in $$source)) {
            this["keyFile"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPConfig($$parsedSource as Partial<SFTPConfig>);
    }
}

/**
 * SMBConfig SMB配置
 */
export class SMBConfig {
    /**
     * 主机地址
     */
    "host": string;

    /**
     * 端口
     */
    "port": number;

    /**
     * 用户名
     */
    "username": string;

    /**
     * 密码
     */
    "password": string;

    /**
     * 共享名称
     */
    "share": string;

    /**
     * 超时时间(秒)
     */
    "timeout": number;

    /** Creates a new SMBConfig instance. */
    constructor($$source: Partial<SMBConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("share" in $$source)) {
            this["share"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMBConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SMBConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMBConfig($$parsedSource as Partial<SMBConfig>);
    }
}

/**
 * TCPUDPConfig TCP/UDP配置
 */
export class TCPUDPConfig {
    /**
     * 主机地址
     */
    "host": string;

    /**
     * 端口
     */
    "port": number;

    /**
     * 超时时间(秒)
     */
    "timeout": number;

    /** Creates a new TCPUDPConfig instance. */
    constructor($$source: Partial<TCPUDPConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TCPUDPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TCPUDPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TCPUDPConfig($$parsedSource as Partial<TCPUDPConfig>);
    }
}

/**
 * TransferResult 传输结果
 */
export class TransferResult {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 消息
     */
    "message": string;

    /**
     * 传输字节数
     */
    "bytes": number;

    /**
     * 耗时(毫秒)
     */
    "time": number;

    /**
     * 速度
     */
    "speed": string;

    /**
     * 本地路径
     */
    "localPath": string;

    /**
     * 远程路径
     */
    "remotePath": string;

    /** Creates a new TransferResult instance. */
    constructor($$source: Partial<TransferResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferResult($$parsedSource as Partial<TransferResult>);
    }
}

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
