// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TCPUDPService TCP/UDP服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectTCP 建立TCP连接
 * @param {$models.TCPUDPConfig} config
 * @returns {Promise<$models.ConnectionStatus | null> & { cancel(): void }}
 */
export function ConnectTCP(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(3702558302, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DisconnectTCP 断开TCP连接
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DisconnectTCP() {
    let $resultPromise = /** @type {any} */($Call.ByID(4097396184));
    return $resultPromise;
}

/**
 * GetConnectionStatus 获取连接状态
 * @returns {Promise<$models.ConnectionStatus | null> & { cancel(): void }}
 */
export function GetConnectionStatus() {
    let $resultPromise = /** @type {any} */($Call.ByID(4252012647));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetUDPServerStatus 获取UDP服务端状态
 * @returns {Promise<$models.ConnectionStatus | null> & { cancel(): void }}
 */
export function GetUDPServerStatus() {
    let $resultPromise = /** @type {any} */($Call.ByID(1953271813));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * HexToString 十六进制转字符串
 * @param {string} hexStr
 * @returns {Promise<string> & { cancel(): void }}
 */
export function HexToString(hexStr) {
    let $resultPromise = /** @type {any} */($Call.ByID(3080971780, hexStr));
    return $resultPromise;
}

/**
 * ReceiveTCP 接收TCP数据
 * @param {number} timeout
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function ReceiveTCP(timeout) {
    let $resultPromise = /** @type {any} */($Call.ByID(305418739, timeout));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ReceiveUDP 接收UDP数据
 * @param {$models.TCPUDPConfig} config
 * @param {number} timeout
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function ReceiveUDP(config, timeout) {
    let $resultPromise = /** @type {any} */($Call.ByID(2535305735, config, timeout));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ReceiveUDPOnServer 在服务端接收UDP数据
 * @param {number} timeout
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function ReceiveUDPOnServer(timeout) {
    let $resultPromise = /** @type {any} */($Call.ByID(342546773, timeout));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SendTCP 发送TCP数据
 * @param {string} data
 * @param {boolean} isHex
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function SendTCP(data, isHex) {
    let $resultPromise = /** @type {any} */($Call.ByID(283679228, data, isHex));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SendUDP 发送UDP数据
 * @param {$models.TCPUDPConfig} config
 * @param {string} data
 * @param {boolean} isHex
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function SendUDP(config, data, isHex) {
    let $resultPromise = /** @type {any} */($Call.ByID(2885643336, config, data, isHex));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SendUDPFromServer 从服务端发送UDP数据到指定客户端
 * @param {string} targetHost
 * @param {number} targetPort
 * @param {string} data
 * @param {boolean} isHex
 * @returns {Promise<$models.MessageResult | null> & { cancel(): void }}
 */
export function SendUDPFromServer(targetHost, targetPort, data, isHex) {
    let $resultPromise = /** @type {any} */($Call.ByID(2013439843, targetHost, targetPort, data, isHex));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * StartUDPServer 启动UDP服务端监听
 * @param {string} host
 * @param {number} port
 * @returns {Promise<$models.ConnectionStatus | null> & { cancel(): void }}
 */
export function StartUDPServer(host, port) {
    let $resultPromise = /** @type {any} */($Call.ByID(4254779055, host, port));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * StopUDPServer 停止UDP服务端
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StopUDPServer() {
    let $resultPromise = /** @type {any} */($Call.ByID(908141213));
    return $resultPromise;
}

/**
 * StringToHex 字符串转十六进制
 * @param {string} str
 * @returns {Promise<string> & { cancel(): void }}
 */
export function StringToHex(str) {
    let $resultPromise = /** @type {any} */($Call.ByID(1514173856, str));
    return $resultPromise;
}

/**
 * TestTCPConnection 测试TCP连接
 * @param {$models.TCPUDPConfig} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestTCPConnection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(1760636882, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestUDPConnection 测试UDP连接
 * @param {$models.TCPUDPConfig} config
 * @returns {Promise<$models.ConnectionResult | null> & { cancel(): void }}
 */
export function TestUDPConnection(config) {
    let $resultPromise = /** @type {any} */($Call.ByID(2231724930, config));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ConnectionStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.MessageResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ConnectionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
