// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TCPUDPService TCP/UDP服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectTCP 建立TCP连接
 */
export function ConnectTCP(config: $models.TCPUDPConfig): Promise<$models.ConnectionStatus | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3702558302, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DisconnectTCP 断开TCP连接
 */
export function DisconnectTCP(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4097396184) as any;
    return $resultPromise;
}

/**
 * GetConnectionStatus 获取连接状态
 */
export function GetConnectionStatus(): Promise<$models.ConnectionStatus | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4252012647) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * HexToString 十六进制转字符串
 */
export function HexToString(hexStr: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3080971780, hexStr) as any;
    return $resultPromise;
}

/**
 * ReceiveTCP 接收TCP数据
 */
export function ReceiveTCP(timeout: number): Promise<$models.MessageResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(305418739, timeout) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ReceiveUDP 接收UDP数据
 */
export function ReceiveUDP(config: $models.TCPUDPConfig, timeout: number): Promise<$models.MessageResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2535305735, config, timeout) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SendTCP 发送TCP数据
 */
export function SendTCP(data: string, isHex: boolean): Promise<$models.MessageResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(283679228, data, isHex) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SendUDP 发送UDP数据
 */
export function SendUDP(config: $models.TCPUDPConfig, data: string, isHex: boolean): Promise<$models.MessageResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2885643336, config, data, isHex) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * StringToHex 字符串转十六进制
 */
export function StringToHex(str: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1514173856, str) as any;
    return $resultPromise;
}

/**
 * TestTCPConnection 测试TCP连接
 */
export function TestTCPConnection(config: $models.TCPUDPConfig): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1760636882, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TestUDPConnection 测试UDP连接
 */
export function TestUDPConnection(config: $models.TCPUDPConfig): Promise<$models.ConnectionResult | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2231724930, config) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.ConnectionStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.MessageResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ConnectionResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
